### ISSUE TITLE
kambrik crashed on startup

### ISSUE THREAD

**Issue by AersafqD** [Chuunkyz/BenchmarkII-1.18#102]
I suddenly crashed while playing with the HMCL launcher, and then I couldn't start it successfully.
The following is the information of the crash window:

A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'kambrik'!
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:159)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'kambrik'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:157)
	... 2 more
Caused by: java.lang.ExceptionInInitializerError
	at io.ejekta.kambrik.internal.KambrikMod.idOf(KambrikMod.kt:30)
	at io.ejekta.kambrik.logging.KambrikMarkers.createIdMarker(KambrikMarkers.kt:16)
	at io.ejekta.kambrik.logging.KambrikMarkers.<clinit>(KambrikMarkers.kt:12)
	at io.ejekta.kambrik.internal.KambrikPrelaunch.handleCustomEntryData(KambrikPrelaunch.kt:31)
	at io.ejekta.kambrik.internal.KambrikPrelaunch.onPreLaunch(KambrikPrelaunch.kt:18)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2588 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_2960.<clinit>(class_2960.java:25)
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	... 14 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method owo(Ljava/lang/String;)Ljava/lang/String; in indrev.mixins.json:aprilfools.MixinTranslatableText from mod indrev failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap indrev-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 17 more

[minecraft-exported-crash-info-2022-04-01T02-09-43.zip](https://github.com/Chuunkyz/BenchmarkII-1.18/files/8392069/minecraft-exported-crash-info-2022-04-01T02-09-43.zip)

**Comment by AersafqD** [comment]
I tried to reinstall modpak, remove kambrik mod and reinstall java17, but none of them solved the problem

**Comment by AersafqD** [comment]
When I changed the date to March 31 (yesterday), there was no more error message. I think this should be some mod's April Fool's Day joke, but it's not funny at all.

**Comment by ManuelKahle** [comment]
Hello, I've got the exact same error. 
Yesterday everything still worked well. Today, all of a sudden, it doesn't.

**Comment by Zarepheth** [comment]
The author of Industrial Revolution was attempting an April Fools Day joke and messed up. Update that mod and you should be good to go.

**Comment by ThornerUA** [comment]
Hi, I've got the same problem and updating Industrial Revolution did nothing to fix that, still the same thing, except mine doesn't crash but instead loads and when i try to joining my old world it says something like "Errors in selected datapacks try launching in safe mode of do this manually" and proceeds to do nothing, after closing the game and checking the logs it says there is an issue with kambrik mod

**Comment by Zarepheth** [comment]
@ThornerUA,

The data pack errors may occur if you started a world with Mod Pack v1.04 or early and then try opening it with Mod Pack v1.05 or later. Manually adding back Better Animals Plus and/or Better Nether should fix the data pack error (at least it fixed that error for me when I added back both of those mods). 

The Kambrik error occurs due to some erroneous code in the Industrial Revolution mod. Mod Pack v1.07 contains the fixed version of the mod, or you can manually update that mod.
—

**Comment by Zarepheth** [comment]
Just an update, I tried removing Better Nether and resetting my Nether dimension (I have not yet done anything important there), and my data pack error returned. I've removed Better Animals Plus and successfully loaded my world after restoring Better Nether to my customizations of the mod pack (currently on v1.07).

**Comment by ThornerUA** [comment]
Thanks, adding better nether and deleting spice of fabric worked.
