### ISSUE TITLE
Game crashes on launch

### ISSUE THREAD

**Issue by pabs68** [Chuunkyz/BenchmarkII-1.18#111]
I just downloaded version 1.0.7 and when I try and launch the game immediately crashes here is the error report:

Here is OS information: Edition	

Windows 11 Home
Version:	21H2
OS build:	22000.593
Experience:	Windows Feature Experience Pack 1000.22000.593.0

System Information:

Processor:	Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz   2.90 GHz
Installed RAM:	44.0 GB
System type:	64-bit operating system, x64-based processor
Video Card:     NVidia 1660 Super with 6 GB VRAM

Uncaught exception in thread "main"
java.lang.RuntimeException: Error creating Mixin config arrp.mixins.json for mod advanced_runtime_resource_pack
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config arrp.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88)
	... 3 more
Caused by: java.lang.IllegalArgumentException: The specified resource 'arrp.mixins.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 6 more

**Comment by mrbeastgaming123** [comment]
Have you tried uninstalling the modpack completely, then reinstalling it?
If you updated the modpack from a pervious version, it won't work

**Comment by pabs68** [comment]
> 



> Have you tried uninstalling the modpack completely, then reinstalling it? If you updated the modpack from a pervious version, it won't work

I have tried manually removing all curseforge/fabric and mod files and reinstalling, I have also since tried on multiple PC's and had the same result so I have given up on this modpack now. For the record I have no problems running other large modpacks such as MCE and All The Mods it is just since the update of this pack.
