### ISSUE TITLE
Server can't be connected to

### ISSUE THREAD

**Issue by madbrad21** [Chuunkyz/BenchmarkII-1.18#126]
I started a server but nobody can connect
I have triple checked port forwarding and know it is correct
I have run many Minecraft servers from this computer yet nobody can connect, it just says can't connect when we try (even when I try to connect to the local IP or direct connect)
The server logs show nothing except the below:

`[23:42:04] [User Authenticator #2/INFO]: UUID of player madbrad21 is 9c6bd6fa-1e3c-4a21-80be-69cb24b9f38e
[23:42:04] [Server thread/INFO]: madbrad21[/192.168.1.34:63551] logged in with entity id 6 at (-150.5, 75.0, -173.5)
[23:42:04] [Server thread/INFO]: madbrad21 joined the game
[23:42:04] [Server thread/INFO]: madbrad21 lost connection: Disconnected
[23:42:04] [Server thread/INFO]: madbrad21 left the game`

Tried vanilla Minecraft and it works fine, we an connect to the server

**Comment by madbrad21** [comment]
I did some more troubleshooting, it appears the startserver.bat runs but fails to download any of the add-ons
the only successes it has are krypton and servercore

[12:17:19] [ERROR] Error while trying to get URL from cursemeta for mod ModEntryRaw(projectID=431823, fileID=3568648)

java.io.IOException: Request to https://cursemeta.dries007.net/431823/3568648.json was not successful.
        at atm.bloodworkxgaming.serverstarter.packtype.curse.CursePackType.downloadMods$lambda-3(CursePackType.kt:203)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by madbrad21** [comment]
Issue resides with server start and will not be working

[https://github.com/Yoosk/ServerStarter/issues/4](https://github.com/Yoosk/ServerStarter/issues/4)
