### ISSUE TITLE
0.4.2 & 0.4.3 server start error

### ISSUE THREAD

**Issue by Norrox** [Chuunkyz/BenchmarkII-1.18#18]
[23:26:08] [main/INFO]: [megane] Loading badasintended.megane.impl.Minecraft from megane-vanilla
[23:26:08] [main/INFO]: [WTHIT] Plugin config reloaded
[23:26:08] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'spectrum'!
        at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.11) ~[?:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.12.12.jar:?]
        at net.minecraft.server.Main.main(Main:106) [server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.12.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.12.jar:?]
        Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_437
                at ru.tlmclub.winterly.WinterlyMod$1.setup(WinterlyMod.java:31) ~[winterly-0.3.0-1.18-fabric.jar:?]
                at io.wispforest.owo.itemgroup.OwoItemGroup.initialize(OwoItemGroup.java:75) ~[owo-lib-0.3.10+1.18.jar:?]
                at ru.tlmclub.winterly.WinterlyMod.onInitialize(WinterlyMod.java:24) ~[winterly-0.3.0-1.18-fabric.jar:?]                at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.12.jar:?]
                at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.12.12.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.12.12.jar:?]
                at net.minecraft.server.Main.main(Main:106) [server-intermediary.jar:?]
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
                at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]                at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
                at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
                at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.12.jar:?]
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
                at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]                at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
                at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.12.jar:?]
        Caused by: java.lang.ClassNotFoundException: net.minecraft.class_437
                at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
                at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
                at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-loader-0.12.12.jar:?]
                at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
                ... 19 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_437
        at de.dafuqs.spectrum.registries.SpectrumItemGroups$1.<init>(SpectrumItemGroups.java:21) ~[spectrum-1.1.5-1.18.1-earlygame6.jar:?]
        at de.dafuqs.spectrum.registries.SpectrumItemGroups.<clinit>(SpectrumItemGroups.java:20) ~[spectrum-1.1.5-1.18.1-earlygame6.jar:?]
        at de.dafuqs.spectrum.registries.SpectrumBlocks.<clinit>(SpectrumBlocks.java:87) ~[spectrum-1.1.5-1.18.1-earlygame6.jar:?]
        at de.dafuqs.spectrum.SpectrumCommon.onInitialize(SpectrumCommon.java:88) ~[spectrum-1.1.5-1.18.1-earlygame6.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.12.jar:?]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_437
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-loader-0.12.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at de.dafuqs.spectrum.registries.SpectrumItemGroups$1.<init>(SpectrumItemGroups.java:21) ~[spectrum-1.1.5-1.18.1-earlygame6.jar:?]
        at de.dafuqs.spectrum.registries.SpectrumItemGroups.<clinit>(SpectrumItemGroups.java:20) ~[spectrum-1.1.5-1.18.1-earlygame6.jar:?]
        at de.dafuqs.spectrum.registries.SpectrumBlocks.<clinit>(SpectrumBlocks.java:87) ~[spectrum-1.1.5-1.18.1-earlygame6.jar:?]
        at de.dafuqs.spectrum.SpectrumCommon.onInitialize(SpectrumCommon.java:88) ~[spectrum-1.1.5-1.18.1-earlygame6.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke

**Comment by internet-person** [comment]
got the exact same error myself.

**Comment by internet-person** [comment]
issue still exists as of 0.4.3.

[19:45:04] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'spectrum'!
        at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.11) ~[?:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.12.12.jar:?]
        at net.minecraft.server.Main.main(Main:106) [server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.12.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.12.jar:?]
        Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_437
                at ru.tlmclub.winterly.WinterlyMod$1.setup(WinterlyMod.java:31) ~[winterly-0.3.0-1.18-fabric.jar:?]
                at io.wispforest.owo.itemgroup.OwoItemGroup.initialize(OwoItemGroup.java:75) ~[owo-lib-0.3.10+1.18.jar:?]
                at ru.tlmclub.winterly.WinterlyMod.onInitialize(WinterlyMod.java:24) ~[winterly-0.3.0-1.18-fabric.jar:?]
                at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.12.jar:?]
                at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.12.12.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.12.12.jar:?]
                at net.minecraft.server.Main.main(Main:106) [server-intermediary.jar:?]
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
                at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
                at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
                at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
                at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.12.jar:?]
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
                at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
                at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
                at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.12.jar:?]
        Caused by: java.lang.ClassNotFoundException: net.minecraft.class_437
                at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
                at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
                at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-loader-0.12.12.jar:?]
                at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
                ... 19 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_437
        at de.dafuqs.spectrum.registries.SpectrumItemGroups$1.<init>(SpectrumItemGroups.java:21) ~[spectrum-1.1.3-1.18.1-earlygame4.jar:?]
        at de.dafuqs.spectrum.registries.SpectrumItemGroups.<clinit>(SpectrumItemGroups.java:20) ~[spectrum-1.1.3-1.18.1-earlygame4.jar:?]
        at de.dafuqs.spectrum.registries.SpectrumBlocks.<clinit>(SpectrumBlocks.java:87) ~[spectrum-1.1.3-1.18.1-earlygame4.jar:?]
        at de.dafuqs.spectrum.SpectrumCommon.onInitialize(SpectrumCommon.java:79) ~[spectrum-1.1.3-1.18.1-earlygame4.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.12.jar:?]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_437
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-loader-0.12.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at de.dafuqs.spectrum.registries.SpectrumItemGroups$1.<init>(SpectrumItemGroups.java:21) ~[spectrum-1.1.3-1.18.1-earlygame4.jar:?]
        at de.dafuqs.spectrum.registries.SpectrumItemGroups.<clinit>(SpectrumItemGroups.java:20) ~[spectrum-1.1.3-1.18.1-earlygame4.jar:?]
        at de.dafuqs.spectrum.registries.SpectrumBlocks.<clinit>(SpectrumBlocks.java:87) ~[spectrum-1.1.3-1.18.1-earlygame4.jar:?]
        at de.dafuqs.spectrum.SpectrumCommon.onInitialize(SpectrumCommon.java:79) ~[spectrum-1.1.3-1.18.1-earlygame4.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.12.jar:?]
        ... 15 more

**Comment by Norrox** [comment]
Benchmark II - 0.4.4 Fixed it
