### ISSUE TITLE
[0.4.5] Crash when joining freshly created single-player world.

### ISSUE THREAD

**Issue by stephen-smith** [Chuunkyz/BenchmarkII-1.18#21]
https://bytebin.lucko.me/bhUG0Tr8V4

```
Description: Exception ticking world

java.lang.IllegalArgumentException: Missing required parameters: [<parameter minecraft:tool>, <parameter minecraft:origin>]
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.12)
	at net.minecraft.loot.context.LootContext$Builder.build(LootContext:208)
	at snownee.snow.loot.NormalLootEntry.generateLoot(NormalLootEntry.java:41)
	at net.minecraft.class_85$1.generateLoot(class_85.java:59)
	at net.minecraft.loot.LootPool.supplyOnce(LootPool:73)
```

**Comment by stephen-smith** [comment]
Second instance on another separately generated world: https://bytebin.lucko.me/ltA7scMOQa
