### ISSUE TITLE
Player getting kicked from server with error and can't load back in again

### ISSUE THREAD

**Issue by YayoDigs** [Chuunkyz/BenchmarkII-1.18#52]
Running a server, version 0.6.4.  Error only occurs when a player out exploring the world and loading new chunks.  Seems like it loads a chuck that has some issue and it will never let that player log in again.   Another Reddit post has same issue.   It is here:
https://www.reddit.com/r/feedthebeast/comments/sa6tmm/benchmark_ii_server_problem/

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 1/22/22, 4:56 PM
Description: Feature placement

java.lang.IllegalStateException: Tag c:end_stones used before it was bound
	at net.minecraft.tag.RequiredTagList$TagWrapper.get(RequiredTagList:84)
	at net.minecraft.tag.RequiredTagList$TagWrapper.contains(RequiredTagList:95)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.isIn(AbstractBlock:982)
	at potionstudios.byg.common.block.BYGLeafPileBlock.canPlantOnTop(BYGLeafPileBlock.java:27)
	at potionstudios.byg.common.block.BYGLeafPileBlock.canPlaceAt(BYGLeafPileBlock.java:33)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.canPlaceAt(AbstractBlock:969)
	at net.minecraft.world.gen.feature.SimpleBlockFeature.generate(SimpleBlockFeature:23)
	at net.minecraft.world.gen.feature.ConfiguredFeature.generate(ConfiguredFeature:80)
	at net.minecraft.world.gen.feature.PlacedFeature.method_39646(PlacedFeature:56)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at net.minecraft.world.gen.feature.PlacedFeature.generate(PlacedFeature:55)
	at net.minecraft.world.gen.feature.PlacedFeature.generateUnregistered(PlacedFeature:40)
	at net.minecraft.world.gen.feature.RandomPatchFeature.generate(RandomPatchFeature:29)
	at net.minecraft.world.gen.feature.ConfiguredFeature.generate(ConfiguredFeature:80)
	at net.minecraft.world.gen.feature.PlacedFeature.method_39646(PlacedFeature:56)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at net.minecraft.world.gen.feature.PlacedFeature.generate(PlacedFeature:55)
	at net.minecraft.world.gen.feature.PlacedFeature.generate(PlacedFeature:44)
	at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator:316)
	at net.minecraft.world.chunk.ChunkStatus.method_20613(ChunkStatus:146)
	at net.minecraft.world.chunk.ChunkStatus.md9111f0$lambda$injectLightmapSetup$1$4(ChunkStatus:546)
	at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus:289)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:605)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:599)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58)
	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:91)
	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:146)
	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:102)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.tag.RequiredTagList$TagWrapper.get(RequiredTagList:84)
	at net.minecraft.tag.RequiredTagList$TagWrapper.contains(RequiredTagList:95)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.isIn(AbstractBlock:982)
	at potionstudios.byg.common.block.BYGLeafPileBlock.canPlantOnTop(BYGLeafPileBlock.java:27)
	at potionstudios.byg.common.block.BYGLeafPileBlock.canPlaceAt(BYGLeafPileBlock.java:33)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.canPlaceAt(AbstractBlock:969)
	at net.minecraft.world.gen.feature.SimpleBlockFeature.generate(SimpleBlockFeature:23)
	at net.minecraft.world.gen.feature.ConfiguredFeature.generate(ConfiguredFeature:80)
	at net.minecraft.world.gen.feature.PlacedFeature.method_39646(PlacedFeature:56)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at net.minecraft.world.gen.feature.PlacedFeature.generate(PlacedFeature:55)
	at net.minecraft.world.gen.feature.PlacedFeature.generateUnregistered(PlacedFeature:40)
	at net.minecraft.world.gen.feature.RandomPatchFeature.generate(RandomPatchFeature:29)
	at net.minecraft.world.gen.feature.ConfiguredFeature.generate(ConfiguredFeature:80)
	at net.minecraft.world.gen.feature.PlacedFeature.method_39646(PlacedFeature:56)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at net.minecraft.world.gen.feature.PlacedFeature.generate(PlacedFeature:55)
	at net.minecraft.world.gen.feature.PlacedFeature.generate(PlacedFeature:44)
	at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator:316)
	at net.minecraft.world.chunk.ChunkStatus.method_20613(ChunkStatus:146)
	at net.minecraft.world.chunk.ChunkStatus.md9111f0$lambda$injectLightmapSetup$1$4(ChunkStatus:546)
	at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus:289)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:605)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:599)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58)
	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:91)
	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:146)
	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:102)
Mixins in Stacktrace: None found

-- Feature --
Details:
	Description: ResourceKey[minecraft:worldgen/placed_feature / byg:clover_flower_patch]
Stacktrace:
	at net.minecraft.class_2794.method_12102(class_2794.java:316)
	at net.minecraft.class_2806.method_20613(class_2806.java:146)
	at net.minecraft.class_2806.md9111f0$lambda$injectLightmapSetup$1$4(class_2806.java:546)
	at net.minecraft.class_2806.method_12154(class_2806.java:289)
	at net.minecraft.class_3898.method_17225(class_3898.java:605)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:599)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Mixins in Stacktrace: Failed to find Mixin metadata: java.lang.NoSuchMethodException: org.spongepowered.asm.mixin.transformer.ClassInfo.getMixins()

-- Generation --
Details:
	CenterX: 0
	CenterZ: -2
	Seed: 6650543830772099007
Stacktrace:
	at net.minecraft.class_2794.method_12102(class_2794.java:316)
	at net.minecraft.class_2806.method_20613(class_2806.java:146)
	at net.minecraft.class_2806.md9111f0$lambda$injectLightmapSetup$1$4(class_2806.java:546)
	at net.minecraft.class_2806.method_12154(class_2806.java:289)
	at net.minecraft.class_3898.method_17225(class_3898.java:605)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:599)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Mixins in Stacktrace: Failed to find Mixin metadata: java.lang.NoSuchMethodException: org.spongepowered.asm.mixin.transformer.ClassInfo.getMixins()

-- Chunk to be generated --
Details:
	Location: 0,-2
	Position hash: -8589934592
	Generator: terrablender.worldgen.TBNoiseBasedChunkGenerator@649ea592
Stacktrace:
	at net.minecraft.class_3898.method_17225(class_3898.java:605)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:599)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Mixins in Stacktrace: Failed to find Mixin metadata: java.lang.NoSuchMethodException: org.spongepowered.asm.mixin.transformer.ClassInfo.getMixins()

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 625
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,71,0), Section: (at 0,7,0 in 1,4,0; chunk contains blocks 16,-64,0 to 31,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 305 game time, 305 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 58078 (now: false), thunder time: 169280 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)
Mixins in Stacktrace: Failed to find Mixin metadata: java.lang.NoSuchMethodException: org.spongepowered.asm.mixin.transformer.ClassInfo.getMixins()

**Comment by YayoDigs** [comment]
updated pack to 0.6.5 and it solved it
