### ISSUE TITLE
Missing dependancies on download/update

### ISSUE THREAD

**Issue by WheresMyMtnDew** [Chuunkyz/BenchmarkII-1.18#6]
Tried several times to get pack to download as it kept throwing a missing dependancies error. On the last test it downloaded but when I tried to launch this is the Uncaught exception thread given from fabric

java.lang.RuntimeException: Error creating Mixin config mixins.cardinal_components_entity.json for mod cardinal-components-entity
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config mixins.cardinal_components_entity.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88)
	... 3 more
Caused by: java.lang.IllegalArgumentException: The specified resource 'mixins.cardinal_components_entity.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 6 more

**Comment by WheresMyMtnDew** [comment]
Strangely after I relaunched it worked fine and I was able to get into game.

**Comment by Chuunkyz** [comment]
that's a problem with the curseforge launcher, but now the problem should be fixed
