### ISSUE TITLE
server fails to start

### ISSUE THREAD

**Issue by internet-person** [Chuunkyz/BenchmarkII-1.18#7]
(0.3.1) this is the only error message i could find:

net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchMethodError: 'net.minecraft.class_2370 net.minecraft.class_2874.method_28517(net.minecraft.class_2378, net.minecraft.class_2378, net.minecraft.class_2378, long)'
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.2)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:604)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66)
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_2370 net.minecraft.class_2874.method_28517(net.minecraft.class_2378, net.minecraft.class_2378, net.minecraft.class_2378, long)'
	at net.minecraft.world.level.storage.LevelStorage.mdd3dcdb$lambda$fixUpDimensionsData$7$0(LevelStorage:590)
	at com.mojang.datafixers.util.Either$Left.mapBoth(Either.java:33)
	at com.mojang.serialization.DataResult.map(DataResult.java:110)
	at net.minecraft.world.level.storage.LevelStorage.fixUpDimensionsData(LevelStorage:574)
	at net.minecraft.world.level.storage.LevelStorage.redirect$dem000$updateDfu(LevelStorage:545)
	at net.minecraft.world.level.storage.LevelStorage.readGeneratorProperties(LevelStorage:114)
	at net.minecraft.world.level.storage.LevelStorage.method_29582(LevelStorage:217)
	at net.minecraft.world.level.storage.LevelStorage.readLevelProperties(LevelStorage:180)
	at net.minecraft.world.level.storage.LevelStorage$Session.readLevelProperties(LevelStorage:324)
	at net.minecraft.server.Main.main(Main:175)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	... 7 more

**Comment by internet-person** [comment]
im mostly sure the meat of the error was in my first post, but incase i missed something this is a copy of the logs folder. tbh i forgot it existed.

[logs.zip](https://github.com/Chuunkyz/BenchmarkII-1.18/files/7697999/logs.zip)

**Comment by internet-person** [comment]
just noticed the other server download with fix in the name and gave it a try, its also broken though that might be because im not running linux, but its also the file you get when downloading via curseforge launcher so if thats the problem it would be cause for concern all the same.

it gave me a ton of errors while running startserver.bat such as "Error while trying to get URL from cursemeta for mod ModEntryRaw(projectID=404410, fileID=3423455)", dozens of the things, and then generally doesnt work because it fails to download basically everything leaving the whole folder at around 10mb.

**Comment by internet-person** [comment]
now working as intended. thank you very much!
