### ISSUE TITLE
Unhandled Fabric Error on launch

### ISSUE THREAD

**Issue by krazykatboy** [Chuunkyz/BenchmarkII-1.18#76]
Got the pack through Curse Forge and I keep getting this error when I try to launch the pack. I tried reinstalling it, repairing both it and minecraft itself, even launching in admin mode, nothing seems to work...

Uncaught exception in thread "main"
java.lang.RuntimeException: error remapping game jars [E:\Curse\Minecraft\Install\versions\fabric-loader-0.13.2-1.18.1\fabric-loader-0.13.2-1.18.1.jar]
	at net.fabricmc.loader.impl.game.GameProviderHelper.deobfuscate(GameProviderHelper.java:219)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.initialize(MinecraftGameProvider.java:281)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:136)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.io.IOException: the jar file E:\Curse\Minecraft\Instances\Benchmark II - 1.18.1\.fabric\remappedJars\minecraft-1.18.1-0.13.2\client-intermediary.jar.tmp can't be written
	at net.fabricmc.tinyremapper.OutputConsumerPath.<init>(OutputConsumerPath.java:114)
	at net.fabricmc.tinyremapper.OutputConsumerPath.<init>(OutputConsumerPath.java:47)
	at net.fabricmc.tinyremapper.OutputConsumerPath$Builder.build(OutputConsumerPath.java:76)
	at net.fabricmc.loader.impl.game.GameProviderHelper.deobfuscate0(GameProviderHelper.java:273)
	at net.fabricmc.loader.impl.game.GameProviderHelper.deobfuscate(GameProviderHelper.java:217)
	... 4 more

**Comment by Chuunkyz** [comment]
idk what launcher you are using, but reinstalling with the curseforge launcher should work
