### ISSUE TITLE
Cannot login with extra alchemy ring

### ISSUE THREAD

**Issue by Morasiu** [Chuunkyz/BenchmarkII-1.18#89]
Version: 1.0.4
Hosting: Bisect Hosting 5 GB

Hi. Amazing mod packs. Just started it playing with my friend! But sadly I cannot play it anymore.

I have a ring of night vision put in my ring slot.

When I try to log in I just get kicked out and cannot login to the server

```
[23.03 14:40:49] [Server] [Server thread/INFO]: Morasiu joined the game
[23.03 14:40:50] [Server] [Server thread/INFO]: [Nbt Crafting] Syncing advanced recipe data to player Morasiu
[23.03 14:40:51] [Server] [Netty Epoll Server IO #2/INFO]: [ShulkerBoxTooltip] Morasiu: protocol version: 2.0
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: java.lang.NoClassDefFoundError: net/minecraft/class_310
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at zabi.minecraft.extraalchemy.items.PotionRingItem.method_7850(PotionRingItem.java:40)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1761.method_7738(class_1761.java:208)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.fabricmc.fabric.api.client.itemgroup.FabricItemGroupBuilder$1.method_7738(FabricItemGroupBuilder.java:129)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at eu.pb4.polymer.impl.networking.packets.PolymerVanillaItemGroupEntry.of(PolymerVanillaItemGroupEntry.java:19)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at eu.pb4.polymer.impl.networking.PolymerServerProtocol.syncVanillaItemGroups(PolymerServerProtocol.java:306)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at eu.pb4.polymer.impl.networking.PolymerServerProtocolHandler.lambda$handleTooltipChange$0(PolymerServerProtocolHandler.java:74)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3738.run(class_3738.java:18)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.redirect$boh000$redirectExecuteTask(class_1255.java:521)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_16075(class_1255.java:125)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:13248)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_5383(class_1255.java:110)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:740)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: net.minecraft.class_310
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	... 16 more
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: java.lang.NoClassDefFoundError: net/minecraft/class_310
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at zabi.minecraft.extraalchemy.items.PotionRingItem.method_7850(PotionRingItem.java:40)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1761.method_7738(class_1761.java:208)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.fabricmc.fabric.api.client.itemgroup.FabricItemGroupBuilder$1.method_7738(FabricItemGroupBuilder.java:129)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at eu.pb4.polymer.impl.networking.packets.PolymerVanillaItemGroupEntry.of(PolymerVanillaItemGroupEntry.java:19)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at eu.pb4.polymer.impl.networking.PolymerServerProtocol.syncVanillaItemGroups(PolymerServerProtocol.java:306)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at eu.pb4.polymer.impl.networking.PolymerServerProtocol.sendSyncPackets(PolymerServerProtocol.java:198)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at eu.pb4.polymer.impl.networking.PolymerServerProtocolHandler.lambda$handleSyncRequest$1(PolymerServerProtocolHandler.java:89)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3738.run(class_3738.java:18)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.redirect$boh000$redirectExecuteTask(class_1255.java:521)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_16075(class_1255.java:125)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:13248)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_5383(class_1255.java:110)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:740)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: net.minecraft.class_310
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	... 17 more
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: java.lang.NoClassDefFoundError: net/minecraft/class_310
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at zabi.minecraft.extraalchemy.items.PotionRingItem.method_7850(PotionRingItem.java:40)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1761.method_7738(class_1761.java:208)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.fabricmc.fabric.api.client.itemgroup.FabricItemGroupBuilder$1.method_7738(FabricItemGroupBuilder.java:129)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at eu.pb4.polymer.impl.networking.packets.PolymerVanillaItemGroupEntry.of(PolymerVanillaItemGroupEntry.java:19)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at eu.pb4.polymer.impl.networking.PolymerServerProtocol.syncVanillaItemGroups(PolymerServerProtocol.java:306)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at eu.pb4.polymer.impl.networking.PolymerServerProtocol.sendSyncPackets(PolymerServerProtocol.java:198)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at eu.pb4.polymer.impl.networking.PolymerServerProtocolHandler.lambda$handleSyncRequest$1(PolymerServerProtocolHandler.java:89)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3738.run(class_3738.java:18)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.redirect$boh000$redirectExecuteTask(class_1255.java:521)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_16075(class_1255.java:125)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:13248)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_5383(class_1255.java:110)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:740)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: net.minecraft.class_310
[23.03 14:40:54] [Server] [Server thread/INFO]: [STDERR]: 	... 17 more
[23.03 14:40:54] [Server] [Server thread/INFO]: [ShulkerBoxTooltip] Loading 2 plugins: inmis, shulkerboxtooltip
[23.03 14:40:54] [Server] [Server thread/INFO]: [ShulkerBoxTooltip] Registered 2 providers for mod inmis
[23.03 14:40:54] [Server] [Server thread/INFO]: [ShulkerBoxTooltip] Registered 7 providers for mod shulkerboxtooltip
[23.03 14:40:57] [Server] [Server thread/INFO]: There are 1 of a max of 60 players online: Morasiu
[23.03 14:41:05] [Disconnect] Morasiu has disconnected, reasonDisconnected
[23.03 14:41:05] [Server] [Server thread/INFO]: Morasiu left the game
[23.03 14:41:05] [Server] [Server thread/WARN]: handleDisconnection() called twice
```

**Comment by Morasiu** [comment]
Nevermind it was not due to the alchemy ring
